import { z } from "zod";

export const cadcpsFormSchema = z.object({
  nome: z.string().min(1),
  field_name: z.string().optional(),
  descricao: z.string().optional().nullable(),
  tipo: z.string().min(1),
  ativo: z.boolean().optional(),
  tela_ids: z.array(z.string()).min(1),
  aplicacao_modo: z.enum(["todas", "especificas"]).optional(),
  empresa_ids: z.array(z.string()).optional(),
  obrigatorio: z.boolean().optional(),
  read_only: z.boolean().optional(),
  visivel_form: z.boolean().optional(),
  visivel_tabela: z.boolean().optional(),
  visivel_relatorio: z.boolean().optional(),
  pesquisavel: z.boolean().optional(),
  filtravel: z.boolean().optional(),
  exportavel: z.boolean().optional(),
  auditavel: z.boolean().optional(),
  placeholder: z.string().optional().nullable(),
  formula: z.string().optional().nullable(),
  calculation_builder: z.any().optional().nullable(),
  usar_mascara: z.boolean().optional(),
  mascaras_text: z.string().optional().nullable(),
  usar_decimal: z.boolean().optional(),
  decimal_places: z.number().optional(),
  separador_decimal: z.string().optional(),
  separador_milhar: z.string().optional(),
  relation_entity: z.string().optional().nullable(),
  opcoes: z.array(z.any()).optional(),
});
