/**
 * Metadata declarativa do módulo Empresas — consumida por defineMakModule().
 * Substitui acoplamento tblEmp.* / formEmp.* dentro da MAK Foundation.
 */
import {
  AGGR_KEY,
  AUTO_FIT_MEASURE_LIMIT,
  COLUNAS_BASE,
  FILTER_POPOVER_WIDTH,
  FROZEN_KEY,
  MAX_AUTO_FIT_WIDTH,
  MIN_COL_WIDTH,
  ORDER_KEY,
  PAGE_SIZE_KEY,
  ROW_DBLCLICK_OPEN_MS,
  ROW_DBLCLICK_PAIR_MS,
  SIZING_MODE_KEY,
  SORT_KEY,
  VISIBLE_KEY,
  WIDTHS_KEY,
  formatHeaderLabel,
  getMinWidth,
} from "@/modules/empresas/components/tblEmp.constants";
import {
  buildEmptyEmpresaForm,
  buildEmpFormDefaultConfig,
  EMP_FORM_BASE_PANELS,
  EMP_FORM_DEFAULT_LAYOUT,
  ESTADOS_BR,
  NATIVE_FIELDS,
  REQUIRED_FIELDS,
  UPPER_FIELDS,
  applyDuplicateFieldClears,
  inputClass,
} from "@/modules/empresas/components/formEmp.constants";
import { buildColunasDisponiveis, loadSavedVisibleColumns, mergeEffectiveColumnLayout } from "@/modules/empresas/utils/empTableColumnCatalog";
import {
  createDefaultColumnFilter,
  evaluateColumnFilter,
  filterNeedsClientSideProcessing,
  getColumnFilterType,
  hasClientOnlyColumnFilters,
  normalizeLegacyColumnFilter,
  parseDateFilterValue,
} from "@/modules/empresas/components/tblEmp.filters";
import { useEmpCamposPersonalizados } from "@/modules/empresas/hooks/useEmpCamposPersonalizados";
import { useFormEmpCustomFields } from "@/modules/empresas/components/formEmp.customFields";
import {
  readStoredFilterOperators,
  writeStoredFilterOperators,
  writeStoredTempListagemFilters,
  readStoredLaunchPanelStyle,
  writeStoredLaunchPanelStyle,
} from "@/modules/empresas/preferences/empresasPreferencesStorage";
import {
  buildColumnSizingModeFromAutoFit,
  mergeColumnSizingMode,
  readEmpTablePreferencesSnapshot,
} from "@/modules/empresas/preferences/empTablePreferencesHydration";
import { emitEmpPreferencesCacheUpdate } from "@/modules/empresas/preferences/empresasPreferencesCache";
import {
  EMP_CARDS_LAYOUT_DEFAULT,
  EMP_CARDS_LAYOUT_OPTIONS,
  EMP_SEARCH_DEFAULT_FIELDS,
  EMP_SEARCH_DROPDOWN_MAX_FIELDS,
  EMP_SEARCH_DROPDOWN_VIS_KEY,
  EMP_SEARCH_FAV_KEY,
  EMP_SEARCH_VIS_KEY,
  EMP_CARDS_LAYOUT_KEY,
  countSearchDropdownVisibleFields,
  getDefaultCardVisFields,
  getEmpSearchFieldValue,
  getFieldsPerRowForLayout,
  buildEmpCardFieldCatalog,
  loadCardsLayoutConfig,
  saveCardsLayoutConfig,
  loadCardFieldOrder,
  loadSearchDropdownVisFields,
  saveSearchDropdownVisFields,
  loadSearchVisFields,
  saveSearchVisFields,
  loadSearchFavorites,
  saveSearchFavorites,
  mergeSearchVisFields,
  sortCardConfigFieldsAlphabetically,
  sortCardConfigFieldsByOrder,
} from "@/modules/empresas/components/empSearchView.constants";
import {
  applyFilterFieldsLayout,
  getDefaultFilterFieldsLayout,
  loadFilterFieldsLayout,
  mergeSavedFilterFieldOrder,
  mergeSavedVisibleFilterFields,
  saveFilterFieldsLayout,
  EMP_FILTER_FIELDS_LAYOUT_KEY,
} from "@/modules/empresas/utils/empFilterFieldsLayout";
import { EMP_VIEW_MODE_STORAGE_KEY } from "@/modules/empresas/preferences/empresasPreferencesStorage";
import { buildEmpresasDynamicFields } from "@/modules/empresas/runtime/empresasFormRuntime.jsx";
import {
  resolveEmpresasComparableValue,
  resolveEmpresasFieldValue,
} from "@/modules/empresas/runtime/empresasTableRuntime.js";
import { buildMakEmpresasSidebarFilterMetadata } from "@/framework/mak/metadata/buildMakFiltersMetadata.js";

export const empresasModuleMetadata = {
  table: {
    columns: COLUNAS_BASE,
    defaultSort: { key: "codempresa", direction: "asc" },
    legacyCleanupKeys: ["emp_col_pinned_right", "emp_group_by_columns_v1"],
    constants: {
      FILTER_POPOVER_WIDTH,
      MIN_COL_WIDTH,
      MAX_AUTO_FIT_WIDTH,
      AUTO_FIT_MEASURE_LIMIT,
      ROW_DBLCLICK_OPEN_MS,
      ROW_DBLCLICK_PAIR_MS,
      formatHeaderLabel,
      getMinWidth,
    },
    preferenceKeys: {
      WIDTHS_KEY,
      FROZEN_KEY,
      VISIBLE_KEY,
      ORDER_KEY,
      AGGR_KEY,
      PAGE_SIZE_KEY,
      SORT_KEY,
      SIZING_MODE_KEY,
    },
    catalog: {
      buildColumnCatalog: buildColunasDisponiveis,
      loadSavedVisibleColumns,
      mergeEffectiveColumnLayout,
    },
    filterHelpers: {
      createDefaultColumnFilter,
      evaluateColumnFilter,
      filterNeedsClientSideProcessing,
      getColumnFilterType,
      hasClientOnlyColumnFilters,
      normalizeLegacyColumnFilter,
      parseDateFilterValue,
    },
    hydration: {
      readTablePreferencesSnapshot: readEmpTablePreferencesSnapshot,
      buildColumnSizingModeFromAutoFit,
      mergeColumnSizingMode,
    },
    storage: {
      readStoredFilterOperators,
      writeStoredFilterOperators,
      writeStoredTempListagemFilters,
    },
    useCustomFieldsHook: useEmpCamposPersonalizados,
    emitCacheUpdate: emitEmpPreferencesCacheUpdate,
    resolveFieldValue: resolveEmpresasFieldValue,
    resolveComparableValue: resolveEmpresasComparableValue,
  },
  form: {
    estados: ESTADOS_BR,
    upperFields: UPPER_FIELDS,
    requiredFields: REQUIRED_FIELDS,
    nativeFields: NATIVE_FIELDS,
    inputClass,
    basePanels: EMP_FORM_BASE_PANELS,
    defaultLayout: EMP_FORM_DEFAULT_LAYOUT,
    buildDefaultConfig: buildEmpFormDefaultConfig,
    buildEmptyRecord: buildEmptyEmpresaForm,
    applyDuplicateFieldClears,
    useRecordFieldsHook: useEmpCamposPersonalizados,
    useCustomFieldsHook: useFormEmpCustomFields,
    buildDynamicFields: buildEmpresasDynamicFields,
    storage: {
      readStoredLaunchPanelStyle,
      writeStoredLaunchPanelStyle,
    },
  },
  preferences: {
    moduleId: "empresas",
    keyPrefix: "emp",
  },
  search: {
    titleField: "razao_social",
    primaryField: "razao_social",
    codeField: "codempresa",
    cardFields: EMP_SEARCH_DEFAULT_FIELDS,
    buildCardCatalog: buildEmpCardFieldCatalog,
    getFieldValue: getEmpSearchFieldValue,
    cardsLayoutDefault: EMP_CARDS_LAYOUT_DEFAULT,
    cardsLayoutOptions: EMP_CARDS_LAYOUT_OPTIONS,
    dropdownMaxFields: EMP_SEARCH_DROPDOWN_MAX_FIELDS,
    getFieldsPerRowForLayout,
    getDefaultCardVisFields,
    countDropdownVisibleFields: countSearchDropdownVisibleFields,
    storageKeys: {
      favoritesKey: EMP_SEARCH_FAV_KEY,
      viewModeKey: EMP_VIEW_MODE_STORAGE_KEY,
      dropdownVisKey: EMP_SEARCH_DROPDOWN_VIS_KEY,
      cardsVisKey: EMP_SEARCH_VIS_KEY,
      cardsLayoutKey: EMP_CARDS_LAYOUT_KEY,
      filterFieldsLayoutKey: EMP_FILTER_FIELDS_LAYOUT_KEY,
    },
    mergeSearchVisFields,
    loadSearchDropdownVisFields,
    saveSearchDropdownVisFields,
    loadSearchVisFields,
    saveSearchVisFields,
    loadCardsLayoutConfig,
    saveCardsLayoutConfig,
    sortCardFieldsAlphabetically: sortCardConfigFieldsAlphabetically,
    sortCardConfigFieldsByOrder,
    loadCardFieldOrder,
    loadFilterFieldsLayout,
    saveFilterFieldsLayout,
    applyFilterFieldsLayout,
    getDefaultFilterFieldsLayout,
    mergeSavedVisibleFilterFields,
    mergeSavedFilterFieldOrder,
    loadSearchFavorites,
    saveSearchFavorites,
  },
  filters: {
    sidebar: buildMakEmpresasSidebarFilterMetadata(),
  },
};
