FROM node:22-alpine

WORKDIR /app

ENV NODE_ENV=production
ENV SEED_SKIP=true
ENV HOST=0.0.0.0

COPY backend/package*.json ./
RUN npm ci

COPY backend/prisma ./prisma
RUN npm run prisma:generate

COPY backend/src ./src
COPY backend/scripts ./scripts
COPY backend/config ./config

EXPOSE 3001

CMD ["node", "src/server.js"]
