export const CADCPS_APLICACAO = {
  TODAS: "todas",
  ESPECIFICAS: "especificas",
};

export const CADCPS_TIPOS = [
  "texto",
  "observacao",
  "inteiro",
  "decimal",
  "moeda",
  "percentual",
  "data",
  "hora",
  "data_hora",
  "sim_nao",
  "email",
  "telefone",
  "cpf",
  "cnpj",
  "cep",
  "rg",
  "url",
  "lista",
  "lista_multipla",
  "relacao",
  "arquivo",
  "imagem",
  "assinatura",
  "formula",
];

export const CADCPS_TELAS_SEED = [
  { codigo: "EMPRESAS", nome: "Empresas", entity_name: "EmpresaCadastro", ordem: 10 },
  { codigo: "FAZENDAS", nome: "Fazendas", entity_name: "FazendaCadastro", ordem: 20 },
  { codigo: "CURRAIS", nome: "Currais", entity_name: "CurralCadastro", ordem: 30 },
  { codigo: "PASTOS", nome: "Pastos", entity_name: "PastoCadastro", ordem: 40 },
  { codigo: "PRODUTOS", nome: "Produtos", entity_name: "ProdutoCadastro", ordem: 50 },
  { codigo: "CLIENTES", nome: "Clientes", entity_name: "ClienteCadastro", ordem: 60 },
  { codigo: "FORNECEDORES", nome: "Fornecedores", entity_name: "FornecedorCadastro", ordem: 70 },
  { codigo: "FUNCIONARIOS", nome: "Funcionários", entity_name: "FuncionarioCadastro", ordem: 80 },
  { codigo: "MAQUINAS", nome: "Máquinas", entity_name: "MaquinaCadastro", ordem: 90 },
  { codigo: "VEICULOS", nome: "Veículos", entity_name: "VeiculoCadastro", ordem: 100 },
  { codigo: "FINANCEIRO", nome: "Financeiro", entity_name: "FinanceiroCadastro", ordem: 110 },
  { codigo: "CENTROS_CUSTO", nome: "Centros de Custo", entity_name: "CentroCustoCadastro", ordem: 120 },
  { codigo: "LANCAMENTOS", nome: "Lançamentos", entity_name: "LancamentoCadastro", ordem: 130 },
];

/** Mapeamento tipo legado → tipo CADCPS */
export const LEGACY_TIPO_TO_CADCPS = {
  text: "texto",
  textarea: "observacao",
  number: "decimal",
  date: "data",
  time: "hora",
  datetime: "data_hora",
  select: "lista",
  option_list: "lista_multipla",
  relation: "relacao",
  calculado: "formula",
  image: "imagem",
  file: "arquivo",
};

/** Mapeamento tipo CADCPS → tipo legado (runtime Empresas / campoEngine) */
export const CADCPS_TIPO_TO_LEGACY = {
  texto: "text",
  observacao: "textarea",
  inteiro: "number",
  decimal: "number",
  moeda: "number",
  percentual: "number",
  data: "date",
  hora: "time",
  data_hora: "datetime",
  sim_nao: "text",
  email: "text",
  telefone: "text",
  cpf: "text",
  cnpj: "text",
  cep: "text",
  rg: "text",
  url: "text",
  lista: "select",
  lista_multipla: "option_list",
  relacao: "relation",
  arquivo: "file",
  imagem: "image",
  assinatura: "file",
  formula: "calculado",
};
