/** Official Studio Component catalog — ModeloBase1 foundation set. */
export const STUDIO_COMPONENT_CATALOG = [
  {
    componentId: "mak.layout.root",
    label: "Layout Root",
    category: "layout",
    icon: "layout-grid",
    description: "Root layout container for cadastro modules.",
    properties: ["label", "visible", "theme"],
    events: ["onLoad"],
    actions: ["open", "navigate"],
    templates: ["modelobase1.cadastro"],
    compatibility: { baseTemplates: ["modelobase1"], engines: ["V13"] },
    runtime: { engine: "V13", render: "CadLayoutConfigurator", preview: "MakCadastroForm" },
  },
  {
    componentId: "mak.section.container",
    label: "Section",
    category: "layout",
    icon: "rows-3",
    description: "Logical section grouping fields and panels.",
    properties: ["label", "visible", "width"],
    events: ["onLoad", "onChange"],
    actions: ["create", "update", "delete"],
    templates: ["modelobase1.section"],
    compatibility: { baseTemplates: ["modelobase1"], engines: ["V13"] },
    runtime: { engine: "V13", render: "CadSection", preview: "CadSection" },
  },
  {
    componentId: "mak.panel.container",
    label: "Panel",
    category: "layout",
    icon: "panel-top",
    description: "Tab/panel container within layout.",
    properties: ["label", "visible", "theme"],
    events: ["onLoad", "onClick"],
    actions: ["open", "navigate"],
    templates: ["modelobase1.panel"],
    compatibility: { baseTemplates: ["modelobase1"], engines: ["V13"] },
    runtime: { engine: "V13", render: "CadPanel", preview: "CadPanel" },
  },
  {
    componentId: "mak.field.native",
    label: "Native Field",
    category: "field",
    icon: "text-cursor-input",
    description: "Native field slot bound to MDP-2 field definition.",
    properties: ["label", "placeholder", "tooltip", "required", "visible", "width"],
    events: ["onChange", "onValidate"],
    actions: ["update"],
    templates: ["modelobase1.field"],
    compatibility: { baseTemplates: ["modelobase1"], engines: ["V14"] },
    runtime: { engine: "V14", render: "RenderEngine", preview: "RenderEngine" },
  },
  {
    componentId: "mak.field.custom",
    label: "Custom Field",
    category: "field",
    icon: "sparkles",
    description: "Custom field from CADCPS catalog.",
    properties: ["label", "placeholder", "required", "visible"],
    events: ["onChange", "onValidate"],
    actions: ["update"],
    templates: ["modelobase1.customField"],
    compatibility: { baseTemplates: ["modelobase1"], engines: ["V14"] },
    runtime: { engine: "V14", render: "useCustomFieldRenderer", preview: "useCustomFieldRenderer" },
  },
  {
    componentId: "mak.view.table",
    label: "Table View",
    category: "view",
    icon: "table",
    description: "List/table view for cadastro modules.",
    properties: ["label", "visible"],
    events: ["onLoad"],
    actions: ["open", "export"],
    templates: ["modelobase1.table"],
    compatibility: { baseTemplates: ["modelobase1"], engines: ["V13"] },
    runtime: { engine: "V13", render: "MakCadastroTable", preview: "MakCadastroTable" },
  },
  {
    componentId: "mak.workflow.graph",
    label: "Workflow Graph",
    category: "workflow",
    icon: "git-branch",
    description: "Workflow step graph designer surface.",
    properties: ["label", "visible"],
    events: ["onWorkflow", "onValidate"],
    actions: ["executeWorkflow", "compile"],
    templates: ["modelobase1.workflow"],
    compatibility: { baseTemplates: ["modelobase1"], engines: ["V20"] },
    runtime: { engine: "V20", render: "WorkflowCanvas", preview: "WorkflowCanvas" },
  },
  {
    componentId: "mak.dashboard.widget",
    label: "Dashboard Widget",
    category: "dashboard",
    icon: "layout-dashboard",
    description: "Dashboard widget placeholder (future Dashboard Studio).",
    properties: ["label", "width", "height", "theme"],
    events: ["onLoad"],
    actions: ["open"],
    templates: ["modelobase1.dashboard"],
    compatibility: { baseTemplates: ["modelobase1"], engines: [] },
    runtime: { engine: null, render: null, preview: null },
  },
];

export default STUDIO_COMPONENT_CATALOG;
