import { deepFreeze } from './deepFreeze.js';

/**
 * Ordered, immutable FUTURE implementation phases for the Preview Sandbox consumer runtime. DECLARATION ONLY.
 * No phase is executed; `implementationStatus` is 'planned' for every phase and `sideEffectsAllowed` is false.
 * Each phase captures objective, future files/functions, inputs/outputs, dependencies, pre/postconditions,
 * issue codes, failure mode, planned tests/gate checks, rollback, and security/performance/acceptance notes.
 */
const P = (order, phaseId, title, spec) => deepFreeze({
  phaseId, order, title,
  objective: spec.objective,
  futureFiles: Object.freeze([...(spec.futureFiles || [])]),
  futureFunctions: Object.freeze([...(spec.futureFunctions || [])]),
  inputs: Object.freeze([...(spec.inputs || [])]),
  outputs: Object.freeze([...(spec.outputs || [])]),
  dependencies: Object.freeze([...(spec.dependencies || [])]),
  preconditions: Object.freeze([...(spec.preconditions || [])]),
  postconditions: Object.freeze([...(spec.postconditions || [])]),
  issueCodes: Object.freeze([...(spec.issueCodes || [])]),
  failureMode: spec.failureMode || 'fail_closed',
  sideEffectsAllowed: false,
  implementationStatus: 'planned',
  testsPlanned: Object.freeze([...(spec.testsPlanned || [])]),
  gateChecksPlanned: Object.freeze([...(spec.gateChecksPlanned || [])]),
  rollbackStrategy: spec.rollbackStrategy || 'rollback_by_non_consumption',
  securityNotes: spec.securityNotes || 'no side effects; synthetic-only; read-only upstreams',
  performanceNotes: spec.performanceNotes || 'deterministic; bounded by resource-limit plan',
  acceptanceCriteria: Object.freeze([...(spec.acceptanceCriteria || [])]),
});

export const PHASE_DEFINITIONS = deepFreeze([
  P(1, 'PHASE_01_RUNTIME_CONFIG_AND_CAPABILITIES', 'Runtime config and capabilities', {
    objective: 'Declare the future runtime config, capability flags and version tuple reflected read-only from the merged contracts.',
    futureFiles: ['runtimeConfig.js', 'runtimeCapabilities.js'],
    futureFunctions: ['isBridgeToPreviewSandboxRuntimeEnabled():boolean', 'isProductionEnv():boolean'],
    inputs: ['config'], outputs: ['frozen runtime config', 'capability manifest'],
    dependencies: [], preconditions: ['contracts merged', 'dev-only flag'],
    postconditions: ['config immutable', 'production disabled'],
    issueCodes: ['RUNTIME_CONFIG_INVALID'], failureMode: 'fail_closed',
    testsPlanned: ['config immutable', 'production returns disabled', 'version tuple exact'],
    gateChecksPlanned: ['config frozen', 'no production access'],
    acceptanceCriteria: ['every runtime flag defaults false', 'version tuple equals contract versions'],
  }),
  P(2, 'PHASE_02_SAFE_INPUT_NORMALIZATION', 'Safe input normalization', {
    objective: 'Reuse the hardened bridge safe-normalization principles (cycle guard, depth cap, JSON-safe policy) before any envelope validation.',
    futureFiles: ['normalizeEnvelopeInput.js'],
    futureFunctions: ['safeNormalizeEnvelopeInput(value,{maxDepth}):{ok,value,issues}'],
    inputs: ['raw envelope candidate'], outputs: ['normalized value or issues'],
    dependencies: ['PHASE_01_RUNTIME_CONFIG_AND_CAPABILITIES'],
    preconditions: ['config ready'], postconditions: ['no cyclic/deep/non-JSON-safe input passes'],
    issueCodes: ['RUNTIME_INPUT_CYCLE', 'RUNTIME_INPUT_TOO_DEEP', 'RUNTIME_INPUT_NON_JSON_SAFE',
      'RUNTIME_INPUT_SPARSE_ARRAY', 'RUNTIME_INPUT_ACCESSOR', 'RUNTIME_INPUT_PROTOTYPE_POLLUTION'],
    failureMode: 'fail_closed_emergency_rejection',
    testsPlanned: ['cycle rejected', 'depth cap enforced', 'accessor rejected', 'proto pollution dropped'],
    gateChecksPlanned: ['depth cap constant present', 'issue codes declared'],
    acceptanceCriteria: ['no unbounded recursion', 'no prototype pollution', 'sanitized rejection'],
  }),
  P(3, 'PHASE_03_ENVELOPE_SHAPE_VALIDATION', 'Envelope shape validation', {
    objective: 'Validate the envelope against the real 17-field envelope shape with no invented fields and required-field presence.',
    futureFiles: ['validateEnvelopeShape.js'],
    futureFunctions: ['validateEnvelopeShape(envelope):issues[]'],
    inputs: ['normalized envelope'], outputs: ['shape issues'],
    dependencies: ['PHASE_02_SAFE_INPUT_NORMALIZATION'],
    preconditions: ['normalized input'], postconditions: ['shape conforms to ENVELOPE_FIELDS'],
    issueCodes: ['RUNTIME_ENVELOPE_REQUIRED', 'RUNTIME_ENVELOPE_INVENTED_FIELD', 'RUNTIME_ENVELOPE_MISSING_REQUIRED_FIELD',
      'RUNTIME_BRIDGE_DECISION_DIGEST_REQUIRED', 'RUNTIME_TARGET_DESCRIPTOR_REQUIRED'],
    failureMode: 'fail_closed',
    testsPlanned: ['missing digest rejected', 'missing descriptor rejected', 'invented field rejected'],
    gateChecksPlanned: ['envelope fields equal contract', 'required subset'],
    acceptanceCriteria: ['digest + descriptor required', 'no invented envelope field accepted'],
  }),
  P(4, 'PHASE_04_DECISION_DIGEST_RECOMPUTE_AND_COMPARE', 'Decision digest recompute-and-compare', {
    objective: 'Reconstruct the decision digest preimage and recompute the FNV digest, comparing byte-for-byte against the carried bridgeDecisionDigest.',
    futureFiles: ['recomputeAndValidateBridgeDecisionDigest.js', 'createDecisionDigest.js'],
    futureFunctions: ['recomputeAndValidateBridgeDecisionDigest(preimage,carriedDigest):issues[]'],
    inputs: ['decision preimage (32 fields)', 'carried bridgeDecisionDigest'], outputs: ['digest match issues'],
    dependencies: ['PHASE_03_ENVELOPE_SHAPE_VALIDATION'],
    preconditions: ['B-RECOMPUTE-INPUT resolved: preimage fields available in envelope'],
    postconditions: ['digest matches or blocker raised'],
    issueCodes: ['RUNTIME_DECISION_DIGEST_MISMATCH', 'RUNTIME_DIGEST_PREIMAGE_INCOMPLETE', 'RUNTIME_DIGEST_SYNTHESIS_FORBIDDEN'],
    failureMode: 'fail_closed',
    testsPlanned: ['exact recompute matches', 'tampered digest rejected', 'incomplete preimage blocks'],
    gateChecksPlanned: ['preimage field count == 32', 'no synthesis/fallback'],
    acceptanceCriteria: ['digest recomputed only from complete preimage', 'no silent fallback'],
    securityNotes: 'FNV is internal identity only; not a security primitive; blocked until B-RECOMPUTE-INPUT resolved',
  }),
  P(5, 'PHASE_05_SAME_DECISION_PROVENANCE_VALIDATION', 'Same-decision provenance validation', {
    objective: 'Prove the digest and descriptor come from the SAME real decision — reject cross-decision mixing, replacement and tampering.',
    futureFiles: ['validateSameDecisionProvenance.js'],
    futureFunctions: ['validateSameDecisionProvenance(envelope):issues[]'],
    inputs: ['digest', 'descriptor'], outputs: ['provenance issues'],
    dependencies: ['PHASE_04_DECISION_DIGEST_RECOMPUTE_AND_COMPARE'],
    preconditions: ['digest recomputed'], postconditions: ['atomic pair enforced'],
    issueCodes: ['RUNTIME_DECISION_DESCRIPTOR_MISMATCH', 'RUNTIME_CROSS_DECISION_MIX_FORBIDDEN',
      'RUNTIME_DESCRIPTOR_REPLACEMENT_FORBIDDEN', 'RUNTIME_DIGEST_REPLACEMENT_FORBIDDEN'],
    failureMode: 'fail_closed',
    testsPlanned: ['digest A + descriptor B rejected', 'descriptor tamper detected', 'status mismatch rejected'],
    gateChecksPlanned: ['recompute-and-compare mode', 'atomic pair required'],
    acceptanceCriteria: ['no cross-decision pair accepted', 'descriptor covered by digest'],
  }),
  P(6, 'PHASE_06_VERSION_TUPLE_VALIDATION', 'Version tuple validation', {
    objective: 'Validate every source/target version against the exact real contract versions — unknown fails closed, no aggregate alias, no silent coercion.',
    futureFiles: ['validateVersionTuple.js'],
    futureFunctions: ['validateVersionTuple(envelope):issues[]'],
    inputs: ['source/target versions'], outputs: ['version issues'],
    dependencies: ['PHASE_05_SAME_DECISION_PROVENANCE_VALIDATION'],
    preconditions: ['provenance validated'], postconditions: ['versions exact'],
    issueCodes: ['RUNTIME_SOURCE_VERSION_MISMATCH', 'RUNTIME_VERSION_UNKNOWN', 'RUNTIME_AGGREGATED_VERSION_ALIAS_FORBIDDEN',
      'RUNTIME_SILENT_VERSION_COERCION_FORBIDDEN'],
    failureMode: 'fail_closed',
    testsPlanned: ['version mismatch rejected', 'unknown version rejected', 'aggregate alias rejected'],
    gateChecksPlanned: ['exact version match', 'unknown fails closed'],
    acceptanceCriteria: ['exact version match required', 'no coercion'],
  }),
  P(7, 'PHASE_07_SYNTHETIC_AND_SECURITY_BOUNDARY_VALIDATION', 'Synthetic and security boundary validation', {
    objective: 'Assert synthetic/immutable/metadataOnly true and every security flag (previewMounted/routeCreated/menuCreated/productExposed/realDataAttached/moduleGenerated/persistenceAllowed) false.',
    futureFiles: ['validateSyntheticBoundary.js', 'validateSecurityBoundary.js'],
    futureFunctions: ['validateSyntheticBoundary(descriptor):issues[]', 'validateSecurityBoundary(descriptor):issues[]'],
    inputs: ['target descriptor'], outputs: ['boundary issues'],
    dependencies: ['PHASE_06_VERSION_TUPLE_VALIDATION'],
    preconditions: ['versions validated'], postconditions: ['no forbidden security flag true'],
    issueCodes: ['RUNTIME_NOT_SYNTHETIC', 'RUNTIME_SECURITY_FLAG_FORBIDDEN', 'RUNTIME_NOT_METADATA_ONLY'],
    failureMode: 'fail_closed',
    testsPlanned: ['non-synthetic rejected', 'previewMounted true rejected', 'productExposed true rejected'],
    gateChecksPlanned: ['security fields enumerated', 'all must be false'],
    acceptanceCriteria: ['synthetic-only enforced', 'no security escalation'],
  }),
  P(8, 'PHASE_08_RESOURCE_LIMIT_ENFORCEMENT', 'Resource limit enforcement', {
    objective: 'Enforce every real resource dimension with the stricter consumer limit, no silent truncation, no partial descriptor.',
    futureFiles: ['enforceRuntimeResourceLimits.js'],
    futureFunctions: ['enforceRuntimeResourceLimits(candidate):issues[]'],
    inputs: ['candidate structure'], outputs: ['limit issues'],
    dependencies: ['PHASE_07_SYNTHETIC_AND_SECURITY_BOUNDARY_VALIDATION'],
    preconditions: ['boundaries validated'], postconditions: ['within limits or blocker'],
    issueCodes: ['RUNTIME_LIMIT_EXCEEDED', 'RUNTIME_UNKNOWN_RESOURCE_DIMENSION'],
    failureMode: 'fail_closed',
    testsPlanned: ['byte limit enforced', 'field limit enforced', 'depth limit enforced'],
    gateChecksPlanned: ['dimensions reflect contract', 'no truncation'],
    acceptanceCriteria: ['no silent truncation', 'no partial descriptor on overflow'],
  }),
  P(9, 'PHASE_09_EXTENSION_VALIDATION', 'Extension validation', {
    objective: 'Validate optional extensions: namespaced, schema-bound, no override of canonical/security/version/digest capabilities.',
    futureFiles: ['validateRuntimeExtensions.js'],
    futureFunctions: ['validateRuntimeExtensions(extensions):issues[]'],
    inputs: ['extensions'], outputs: ['extension issues'],
    dependencies: ['PHASE_08_RESOURCE_LIMIT_ENFORCEMENT'],
    preconditions: ['limits enforced'], postconditions: ['no privileged override'],
    issueCodes: ['RUNTIME_EXTENSION_UNNAMESPACED_FORBIDDEN', 'RUNTIME_EXTENSION_MISSING_SCHEMA',
      'RUNTIME_EXTENSION_CAPABILITY_OVERRIDE_FORBIDDEN'],
    failureMode: 'fail_closed',
    testsPlanned: ['unnamespaced rejected', 'capability override rejected'],
    gateChecksPlanned: ['override list enumerated'],
    acceptanceCriteria: ['no extension enables product/mount/certification'],
  }),
  P(10, 'PHASE_10_MAPPING_CONTRACT_VALIDATION', 'Mapping contract validation', {
    objective: 'Validate the 12 real field mappings: known source fields, no invented target, allowed transforms, no default, lossless, no duplicate.',
    futureFiles: ['validateMappingContract.js'],
    futureFunctions: ['validateMappingContract(mappings):issues[]'],
    inputs: ['field mapping contract'], outputs: ['mapping issues'],
    dependencies: ['PHASE_09_EXTENSION_VALIDATION'],
    preconditions: ['extensions validated'], postconditions: ['mapping set equals real 12'],
    issueCodes: ['RUNTIME_MAPPING_SOURCE_FIELD_MISSING', 'RUNTIME_MAPPING_TARGET_FIELD_INVENTED',
      'RUNTIME_MAPPING_UNKNOWN_TRANSFORM', 'RUNTIME_MAPPING_DEFAULT_FORBIDDEN', 'RUNTIME_MAPPING_DUPLICATE_FORBIDDEN'],
    failureMode: 'fail_closed',
    testsPlanned: ['12 mappings validated', 'unknown transform rejected', 'default rejected'],
    gateChecksPlanned: ['mapping count == 12', 'transforms from allowlist'],
    acceptanceCriteria: ['no local divergent mapping list', 'lossless enforced'],
  }),
  P(11, 'PHASE_11_FIELD_MAPPING_EXECUTION', 'Field mapping execution', {
    objective: 'Execute the 12 mappings in fixed order via clone semantics into the future sandbox descriptor fields — no default, no loss, no duplicate target.',
    futureFiles: ['executeFieldMappings.js'],
    futureFunctions: ['executeFieldMappings(descriptor,mappings):{mapped,issues}'],
    inputs: ['validated descriptor', 'mapping contract'], outputs: ['mapped fields'],
    dependencies: ['PHASE_10_MAPPING_CONTRACT_VALIDATION'],
    preconditions: ['mapping contract valid'], postconditions: ['every required target field covered'],
    issueCodes: ['RUNTIME_MAPPING_LOSSY_FORBIDDEN', 'RUNTIME_MAPPING_TARGET_COLLISION_FORBIDDEN'],
    failureMode: 'fail_closed',
    testsPlanned: ['mapped values equal source', 'assert_true transforms enforced', 'envelope_metadata cloned'],
    gateChecksPlanned: ['target coverage complete', 'clone not reference'],
    acceptanceCriteria: ['deterministic order', 'no source mutation'],
  }),
  P(12, 'PHASE_12_SANDBOX_DESCRIPTOR_BUILD', 'Sandbox descriptor build', {
    objective: 'Build the metadata-only sandbox descriptor from the mapped fields, only after all blockers pass.',
    futureFiles: ['createSandboxDescriptor.js'],
    futureFunctions: ['createSandboxDescriptor(mapped):sandboxDescriptor'],
    inputs: ['mapped fields'], outputs: ['sandbox descriptor (metadata-only)'],
    dependencies: ['PHASE_11_FIELD_MAPPING_EXECUTION'],
    preconditions: ['all prior blockers passed'], postconditions: ['descriptor metadata-only, immutable'],
    issueCodes: ['RUNTIME_PARTIAL_DESCRIPTOR_FORBIDDEN'],
    failureMode: 'fail_closed',
    testsPlanned: ['descriptor metadataOnly true', 'no partial descriptor on blocker'],
    gateChecksPlanned: ['builder flag false in plan', 'required fields covered'],
    acceptanceCriteria: ['descriptor only after green pipeline', 'immutable output'],
  }),
  P(13, 'PHASE_13_SANDBOX_DESCRIPTOR_VALIDATION', 'Sandbox descriptor validation', {
    objective: 'Validate the built descriptor against the real future sandbox descriptor shape and security invariants.',
    futureFiles: ['validateSandboxDescriptor.js'],
    futureFunctions: ['validateSandboxDescriptor(descriptor):issues[]'],
    inputs: ['sandbox descriptor'], outputs: ['descriptor issues'],
    dependencies: ['PHASE_12_SANDBOX_DESCRIPTOR_BUILD'],
    preconditions: ['descriptor built'], postconditions: ['descriptor conforms to contract'],
    issueCodes: ['RUNTIME_SANDBOX_DESCRIPTOR_SHAPE_INVALID', 'RUNTIME_SANDBOX_SECURITY_FLAG_FORBIDDEN'],
    failureMode: 'fail_closed',
    testsPlanned: ['required fields present', 'security flags false'],
    gateChecksPlanned: ['shape equals contract futureFields'],
    acceptanceCriteria: ['descriptor validated true', 'no security escalation'],
  }),
  P(14, 'PHASE_14_CONSUMER_DECISION_BUILD', 'Consumer decision build', {
    objective: 'Build the deterministic consumer decision with canonical serializer, decision digest, ordered issues and success/failure status.',
    futureFiles: ['createConsumerDecision.js'],
    futureFunctions: ['createConsumerDecision(state):consumerDecision'],
    inputs: ['pipeline state'], outputs: ['consumer decision + consumerDecisionDigest'],
    dependencies: ['PHASE_13_SANDBOX_DESCRIPTOR_VALIDATION'],
    preconditions: ['descriptor validated'], postconditions: ['atomic decision with digest'],
    issueCodes: ['RUNTIME_CONSUMER_DECISION_INVALID'],
    failureMode: 'fail_closed',
    testsPlanned: ['accepted status on green', 'rejected status on blocker', 'digest deterministic'],
    gateChecksPlanned: ['statuses from allowlist', 'digest not cryptographic claim'],
    acceptanceCriteria: ['deterministic digest', 'FNV internal identity only'],
  }),
  P(15, 'PHASE_15_FAILURE_CONTAINMENT_AND_EMERGENCY_REJECTION', 'Failure containment and emergency rejection', {
    objective: 'Contain all failures atomically: null descriptor on blocker, no partial output, no source mutation, sanitized emergency rejection on unexpected exceptions.',
    futureFiles: ['createFailureContainment.js', 'createEmergencyConsumerRejection.js'],
    futureFunctions: ['createEmergencyConsumerRejection(reason):consumerDecision'],
    inputs: ['error/blocker state'], outputs: ['sanitized rejection'],
    dependencies: ['PHASE_14_CONSUMER_DECISION_BUILD'],
    preconditions: ['public boundary wrapped'], postconditions: ['no leak, fail closed'],
    issueCodes: ['RUNTIME_UNEXPECTED_EXECUTION_FAILURE'],
    failureMode: 'fail_closed_emergency_rejection',
    testsPlanned: ['exception yields sanitized rejection', 'no stack/message leak', 'rollback by non-consumption'],
    gateChecksPlanned: ['public try/catch planned', 'no leak fields'],
    acceptanceCriteria: ['no partial descriptor', 'no secret/stack leak'],
  }),
  P(16, 'PHASE_16_REPLAY_IDEMPOTENCY_AND_DETERMINISM', 'Replay, idempotency and determinism', {
    objective: 'Guarantee same envelope + same config → same decision, same issue ordering, same descriptor, same digest, across instances; no ambient clock/random/locale/timezone.',
    futureFiles: ['createReplayContract.js'],
    futureFunctions: ['assertDeterministicReplay(a,b):boolean (planned)'],
    inputs: ['two identical runs'], outputs: ['determinism proof'],
    dependencies: ['PHASE_15_FAILURE_CONTAINMENT_AND_EMERGENCY_REJECTION'],
    preconditions: ['no global mutable state'], postconditions: ['bit-identical decisions'],
    issueCodes: ['RUNTIME_NONDETERMINISM_FORBIDDEN'],
    failureMode: 'fail_closed',
    testsPlanned: ['replay identical', 'cross-instance identical', 'no ambient clock or random source'],
    gateChecksPlanned: ['static nondeterminism scan', 'no ambient clock'],
    acceptanceCriteria: ['deterministic across instances', 'no randomness/locale/timezone'],
  }),
  P(17, 'PHASE_17_MANIFEST_VERIFIER_READINESS', 'Manifest, verifier and readiness', {
    objective: 'Provide the runtime manifest (part digests + overall), fail-closed verifier, compatibility check and readiness decision.',
    futureFiles: ['createRuntimeManifest.js', 'verifyRuntime.js', 'checkRuntimeCompatibility.js',
      'createRuntimeDiagnostics.js', 'createRuntimeReadinessDecision.js'],
    futureFunctions: ['verifyRuntime({runtime}):verification', 'checkRuntimeCompatibility():compatibility'],
    inputs: ['runtime object'], outputs: ['manifest', 'verification', 'readiness'],
    dependencies: ['PHASE_16_REPLAY_IDEMPOTENCY_AND_DETERMINISM'],
    preconditions: ['runtime composed'], postconditions: ['verifier fail-closed'],
    issueCodes: ['RUNTIME_VERIFICATION_FAILED'],
    failureMode: 'fail_closed',
    testsPlanned: ['manifest deterministic', 'verifier detects tamper', 'compatibility green'],
    gateChecksPlanned: ['manifest overallDigest stable', 'verifier tamper battery'],
    acceptanceCriteria: ['deterministic manifest', 'verifier blocks premature runtime'],
  }),
  P(18, 'PHASE_18_TEST_GATE_EVIDENCE_CERTIFICATION', 'Test, gate and evidence certification', {
    objective: 'Deliver the future runtime test (>= 900 asserts), gate (>= 280 checks), evidence and the manual pre-mount checkpoint.',
    futureFiles: ['(test + gate + evidence — separate slice)'],
    futureFunctions: [],
    inputs: ['runtime + manifest'], outputs: ['certified runtime evidence'],
    dependencies: ['PHASE_17_MANIFEST_VERIFIER_READINESS'],
    preconditions: ['runtime verified'], postconditions: ['manual checkpoint gate reached'],
    issueCodes: [], failureMode: 'fail_closed',
    testsPlanned: ['runtime test >= 900', 'gate >= 280', 'bundle absence'],
    gateChecksPlanned: ['scope', 'registry', 'no dependency', 'bundle absence'],
    acceptanceCriteria: ['manual checkpoint required before preview mount', 'no auto product exposure'],
  }),
]);

export const PHASE_IDS = deepFreeze(PHASE_DEFINITIONS.map((p) => p.phaseId));
export const PHASE_COUNT = PHASE_DEFINITIONS.length;
export default PHASE_DEFINITIONS;
