export {
  MDP_PLATFORM_VERSION_ID,
  DEFAULT_LOCALE,
  MDP_ENTITY_IDS,
} from "./mdpEntityConstants.js";

/** Stable relationship IDs for platform seed (EmpresaCadastro pilot). */
export const MDP_RELATIONSHIP_IDS = {
  empresaCliente: "EmpresaCadastro.cliente",
  empresaCadastros: "EmpresaCadastro.cadastro_registros",
  empresaAnexos: "EmpresaCadastro.anexos",
  empresaPermissoes: "EmpresaCadastro.permissoes",
  empresaCustomFields: "EmpresaCadastro.custom_fields",
  empresaFieldScopes: "EmpresaCadastro.field_empresa_scopes",
};

/** System entities required for relationship graph (not runtime modules). */
export const SYSTEM_ENTITY_DEFS = [
  {
    entity_id: "Cliente",
    module_id: "platform-core",
    codigo: "CLIENTE",
    entity_kind: "system",
    legacy_entity_name: "Cliente",
    persistence: { prismaModel: "Cliente", tableName: "Cliente", primaryKey: "id" },
    labels: { singular: "Cliente", plural: "Clientes", description: "Tenant raiz da plataforma" },
  },
  {
    entity_id: "CadastroRegistro",
    module_id: "platform-core",
    codigo: "CADREG",
    entity_kind: "system",
    legacy_entity_name: "CadastroRegistro",
    persistence: { prismaModel: "CadastroRegistro", tableName: "CadastroRegistro", primaryKey: "id" },
    labels: { singular: "Registro de Cadastro", plural: "Registros de Cadastro" },
  },
  {
    entity_id: "RegistroAnexo",
    module_id: "platform-core",
    codigo: "ANEXO",
    entity_kind: "system",
    legacy_entity_name: "RegistroAnexo",
    persistence: { prismaModel: "RegistroAnexo", tableName: "RegistroAnexo", primaryKey: "id" },
    labels: { singular: "Anexo", plural: "Anexos" },
  },
  {
    entity_id: "PermissaoEmpresa",
    module_id: "platform-core",
    codigo: "PERMEMP",
    entity_kind: "system",
    legacy_entity_name: "PermissaoEmpresa",
    persistence: { prismaModel: "PermissaoEmpresa", tableName: "PermissaoEmpresa", primaryKey: "id" },
    labels: { singular: "Permissão de Empresa", plural: "Permissões de Empresa" },
  },
];

export const PLATFORM_RELATIONSHIP_DEFS = [
  {
    relationship_id: MDP_RELATIONSHIP_IDS.empresaCliente,
    from_entity_id: "EmpresaCadastro",
    to_entity_id: "Cliente",
    kind: "physical",
    relationship_type: "one_to_one",
    semantics: "composition",
    dependency: "cascade",
    dependency_class: "data",
    cardinality: { minFrom: 1, maxFrom: 1, minTo: 0, maxTo: null },
    fk_mapping: { fromField: "cliente_id", toField: "id" },
    label: "Pertence ao Cliente",
    description: "Ownership multi-tenant — Empresa → Cliente",
    sort_order: 10,
  },
  {
    relationship_id: MDP_RELATIONSHIP_IDS.empresaCadastros,
    from_entity_id: "EmpresaCadastro",
    to_entity_id: "CadastroRegistro",
    kind: "physical",
    relationship_type: "one_to_many",
    semantics: "aggregation",
    dependency: "restrict",
    dependency_class: "data",
    cardinality: { minFrom: 0, maxFrom: null, minTo: 1, maxTo: 1 },
    fk_mapping: { fromField: "id", toField: "empresa_id" },
    empresa_scoped: true,
    label: "Registros de Cadastro",
    description: "Empresa possui registros genéricos de cadastro",
    sort_order: 20,
  },
  {
    relationship_id: MDP_RELATIONSHIP_IDS.empresaAnexos,
    from_entity_id: "EmpresaCadastro",
    to_entity_id: "RegistroAnexo",
    kind: "physical",
    relationship_type: "one_to_many",
    semantics: "composition",
    dependency: "cascade",
    dependency_class: "data",
    cardinality: { minFrom: 0, maxFrom: null, minTo: 0, maxTo: 1 },
    fk_mapping: { fromField: "id", toField: "empresa_id" },
    empresa_scoped: true,
    label: "Anexos",
    description: "Anexos vinculados à empresa",
    sort_order: 30,
  },
  {
    relationship_id: MDP_RELATIONSHIP_IDS.empresaPermissoes,
    from_entity_id: "EmpresaCadastro",
    to_entity_id: "PermissaoEmpresa",
    kind: "physical",
    relationship_type: "one_to_many",
    semantics: "association",
    dependency: "cascade",
    dependency_class: "permission",
    cardinality: { minFrom: 0, maxFrom: null, minTo: 1, maxTo: 1 },
    fk_mapping: { fromField: "id", toField: "empresa_id" },
    label: "Permissões por Empresa",
    description: "RBAC multi-empresa",
    sort_order: 40,
  },
  {
    relationship_id: MDP_RELATIONSHIP_IDS.empresaCustomFields,
    from_entity_id: "EmpresaCadastro",
    to_entity_id: "CadcpsFieldCatalog",
    kind: "logical",
    relationship_type: "one_to_many",
    semantics: "dependency",
    dependency: "optional",
    dependency_class: "data",
    cardinality: { minFrom: 0, maxFrom: null, minTo: 0, maxTo: null },
    label: "Campos Personalizados",
    description: "Campos custom via Data Dictionary (MDP-2)",
    sort_order: 50,
  },
  {
    relationship_id: MDP_RELATIONSHIP_IDS.empresaFieldScopes,
    from_entity_id: "EmpresaCadastro",
    to_entity_id: "EmpresaCadastro",
    kind: "logical",
    relationship_type: "many_to_many",
    semantics: "association",
    dependency: "optional",
    dependency_class: "layout",
    enabled: false,
    metadata: { reserved: true, consumer: "Field Studio", phase: "MDP-4+" },
    cardinality: { minFrom: 0, maxFrom: null, minTo: 0, maxTo: null },
    label: "Escopo de Campos por Empresa",
    description: "Reservado — layout/field scope (desabilitado v1)",
    sort_order: 900,
  },
  {
    relationship_id: "EmpresaCadastro.workflow_dependencies",
    from_entity_id: "EmpresaCadastro",
    to_entity_id: "EmpresaCadastro",
    kind: "logical",
    relationship_type: "one_to_many",
    semantics: "dependency",
    dependency_class: "workflow",
    enabled: false,
    metadata: { reserved: true, consumer: "Workflow Studio", phase: "MDP-4+" },
    cardinality: { minFrom: 0, maxFrom: null, minTo: 0, maxTo: null },
    label: "Dependências de Workflow",
    sort_order: 910,
  },
  {
    relationship_id: "EmpresaCadastro.ai_context",
    from_entity_id: "EmpresaCadastro",
    to_entity_id: "EmpresaCadastro",
    kind: "computed",
    relationship_type: "one_to_many",
    semantics: "dependency",
    dependency_class: "ai_context",
    enabled: false,
    metadata: { reserved: true, consumer: "AI Platform", phase: "MDP-4+" },
    cardinality: { minFrom: 0, maxFrom: null, minTo: 0, maxTo: null },
    label: "Contexto IA",
    sort_order: 920,
  },
];
