import { createHash } from "node:crypto";

export {
  MDP_PLATFORM_VERSION_ID,
  DEFAULT_LOCALE,
} from "./mdpEntityConstants.js";

export const REGISTRY_SCHEMA_VERSION = "1.0.0";

/** All MDP-4 entry types supported by the platform registry. */
export const MDP_REGISTRY_ENTRY_TYPES = [
  "layout",
  "view",
  "form",
  "section",
  "panel",
  "tab",
  "group",
  "field",
  "field_config",
  "action",
  "event",
  "formula",
  "validation",
  "workflow",
  "dashboard",
  "pivot_table",
  "report",
  "permission",
  "automation",
  "base_template",
  "template",
  "integration",
  "ai_definition",
  "studio_definition",
  "theme",
];

export const hashRegistryPayload = (payload) =>
  createHash("sha256").update(JSON.stringify(payload)).digest("hex");

/** Minimal JSON Schema contracts per entry type (v1). */
export const REGISTRY_SCHEMA_STUBS = MDP_REGISTRY_ENTRY_TYPES.map((entryType) => ({
  entry_type: entryType,
  schema_version: REGISTRY_SCHEMA_VERSION,
  json_schema: {
    $schema: "https://json-schema.org/draft/2020-12/schema",
    type: "object",
    title: `MdpRegistryEntry:${entryType}`,
    additionalProperties: true,
    properties: {
      entryId: { type: "string" },
      moduleId: { type: "string" },
      entityId: { type: "string" },
      baseTemplateId: { type: "string" },
    },
  },
}));

/** Platform seed entries for empresas pilot (declarative payloads only). */
export const EMPRESAS_REGISTRY_SEED = [
  {
    entry_id: "empresas.base_template.modelobase1",
    entry_type: "base_template",
    module_id: "empresas",
    entity_id: "EmpresaCadastro",
    status: "published",
    label: "ModeloBase1 — Cadastro",
    description: "Base Template 1 — listagem + formulário cadastro",
    payload: {
      baseTemplateId: "modelobase1",
      runtimeEntry: "ModeloBase1CadastroPage",
      compatibleEngines: ["V13", "V14", "V16", "V17", "V18", "V19", "V20"],
      pattern: "cadastro-list-form",
    },
    bindings: [{ binding_kind: "entity", target_id: "EmpresaCadastro" }],
    sort_order: 10,
  },
  {
    entry_id: "empresas.layout.main",
    entry_type: "layout",
    module_id: "empresas",
    entity_id: "EmpresaCadastro",
    status: "published",
    label: "Layout Principal Empresas",
    payload: {
      layoutKey: "empresas.main",
      panels: ["identificacao", "endereco", "contato", "observacoes"],
      defaultLayoutRef: "empresas.form.default",
    },
    bindings: [
      { binding_kind: "entity", target_id: "EmpresaCadastro" },
      { binding_kind: "module", target_id: "empresas" },
    ],
    sort_order: 20,
  },
  {
    entry_id: "empresas.form.default",
    entry_type: "form",
    module_id: "empresas",
    entity_id: "EmpresaCadastro",
    status: "published",
    label: "Formulário Empresas",
    payload: {
      formKey: "empresas.cadastro",
      nativeFieldCount: 20,
      panelsRef: "empresas.layout.main",
      requiredFields: ["tipo_pessoa", "razao_social"],
    },
    bindings: [{ binding_kind: "entity", target_id: "EmpresaCadastro" }],
    sort_order: 30,
  },
  {
    entry_id: "empresas.field_config.native",
    entry_type: "field_config",
    module_id: "empresas",
    entity_id: "EmpresaCadastro",
    status: "published",
    label: "Field Config — Campos Nativos",
    payload: {
      engine: "V14",
      source: "EMP_FORM_FIELD_DEFS",
      nativeFields: [
        "codempresa", "razao_social", "nome_fantasia", "tipo_pessoa", "status",
      ],
    },
    bindings: [{ binding_kind: "entity", target_id: "EmpresaCadastro" }],
    sort_order: 40,
  },
  {
    entry_id: "empresas.validation.default",
    entry_type: "validation",
    module_id: "empresas",
    entity_id: "EmpresaCadastro",
    status: "published",
    label: "Validation Config Empresas",
    payload: {
      engine: "V16",
      rules: [
        { field: "razao_social", rule: "required" },
        { field: "tipo_pessoa", rule: "required" },
        { field: "cpf_cnpj", rule: "cpf_cnpj_by_tipo_pessoa" },
      ],
    },
    bindings: [{ binding_kind: "entity", target_id: "EmpresaCadastro" }],
    sort_order: 50,
  },
  {
    entry_id: "empresas.view.table",
    entry_type: "view",
    module_id: "empresas",
    entity_id: "EmpresaCadastro",
    status: "published",
    label: "View Tabela Empresas",
    payload: { viewType: "table", defaultSort: { key: "codempresa", direction: "asc" } },
    sort_order: 60,
  },
  {
    entry_id: "empresas.section.identificacao",
    entry_type: "section",
    module_id: "empresas",
    status: "published",
    label: "Seção Identificação",
    payload: { sectionKey: "identificacao", fields: ["tipo_pessoa", "razao_social", "cpf_cnpj"] },
    sort_order: 70,
  },
  {
    entry_id: "empresas.panel.main",
    entry_type: "panel",
    module_id: "empresas",
    status: "published",
    label: "Panel Principal",
    payload: { panelKey: "main", sections: ["identificacao", "endereco"] },
    sort_order: 80,
  },
  {
    entry_id: "empresas.permission.resource",
    entry_type: "permission",
    module_id: "empresas",
    status: "published",
    label: "RBAC Empresas",
    payload: { resourceKey: "empresas", actions: ["read", "create", "update", "delete"] },
    sort_order: 90,
  },
  {
    entry_id: "empresas.event.catalog",
    entry_type: "event",
    module_id: "empresas",
    status: "published",
    label: "Events Catalog Empresas",
    payload: { engine: "V18", events: ["onSave", "onDelete", "onDuplicateClear"] },
    sort_order: 100,
  },
  {
    entry_id: "empresas.action.catalog",
    entry_type: "action",
    module_id: "empresas",
    status: "published",
    label: "Actions Catalog Empresas",
    payload: { engine: "V19", actions: ["save", "cancel", "new"] },
    sort_order: 110,
  },
  {
    entry_id: "empresas.formula.catalog",
    entry_type: "formula",
    module_id: "empresas",
    status: "published",
    label: "Formula Catalog Empresas",
    payload: { engine: "V17", formulas: [] },
    sort_order: 120,
  },
  {
    entry_id: "empresas.workflow.catalog",
    entry_type: "workflow",
    module_id: "empresas",
    status: "published",
    label: "Workflow Catalog Empresas",
    payload: { engine: "V20", workflows: [] },
    sort_order: 130,
  },
  {
    entry_id: "empresas.dashboard.main",
    entry_type: "dashboard",
    module_id: "empresas",
    enabled: false,
    status: "draft",
    label: "Dashboard Empresas (reservado)",
    payload: { reserved: true, consumer: "Dashboard Studio", phase: "MDP-5+" },
    metadata: { reserved: true },
    sort_order: 900,
  },
  {
    entry_id: "empresas.pivot.default",
    entry_type: "pivot_table",
    module_id: "empresas",
    enabled: false,
    status: "draft",
    label: "Pivot Empresas (reservado)",
    payload: { reserved: true, consumer: "Pivot Studio" },
    sort_order: 910,
  },
  {
    entry_id: "empresas.report.default",
    entry_type: "report",
    module_id: "empresas",
    enabled: false,
    status: "draft",
    label: "Relatório Empresas (reservado)",
    payload: { reserved: true, consumer: "Report Studio" },
    sort_order: 920,
  },
  {
    entry_id: "empresas.automation.default",
    entry_type: "automation",
    module_id: "empresas",
    enabled: false,
    status: "draft",
    label: "Automação Empresas (reservado)",
    payload: { reserved: true, consumer: "Automation Studio" },
    sort_order: 930,
  },
  {
    entry_id: "empresas.integration.default",
    entry_type: "integration",
    module_id: "empresas",
    enabled: false,
    status: "draft",
    label: "Integração Empresas (reservado)",
    payload: { reserved: true, consumer: "Platform Core" },
    sort_order: 940,
  },
  {
    entry_id: "empresas.ai.context",
    entry_type: "ai_definition",
    module_id: "empresas",
    enabled: false,
    status: "draft",
    label: "Definição IA Empresas (reservado)",
    payload: { reserved: true, consumer: "AI Platform" },
    sort_order: 950,
  },
  {
    entry_id: "empresas.studio.module",
    entry_type: "studio_definition",
    module_id: "empresas",
    enabled: false,
    status: "draft",
    label: "Studio Definition Empresas (reservado)",
    payload: { reserved: true, consumer: "MAK Studio" },
    sort_order: 960,
  },
];
