/** Field Configuration Engine oficial do ModeloBase1 — re-export da Foundation MAK. */
export {
  buildMakFieldConfigMetadata,
  normalizeMakFieldMetadata,
  MAK_FIELD_METADATA_KEYS,
  buildMakDynamicFieldsFromMetadata,
  resolveMakFieldType,
  buildMakDynamicFieldsWithCustomFields,
  appendMakCustomDynamicFields,
  createMakFieldConfigEngine,
  registerMakFieldConfigEngine,
  getMakFieldConfigEngine,
  listMakFieldConfigEngines,
  hasMakFieldConfigEngine,
  MAK_FIELD_CERTIFICATION_CATALOG,
  MAK_FIELD_CERTIFICATION_LAYOUT,
  MAK_FIELD_ENGINE_INVENTORY,
  listMakFieldEngineTypes,
  FieldEngine,
  getFieldTypeDefinition,
  listFieldTypes,
  registerFieldType,
  registerBuiltinFieldTypes,
  ensureBuiltinFieldTypes,
  CustomFieldEngine,
  useCustomFieldRenderer,
  RenderEngine,
  buildMakStandardDynamicFields,
} from "@/framework/mak/fieldConfig/index.js";
