/** Official Studio Event Hub catalog — Program 2.0.7. */

const baseManifest = (overrides) => ({
  priority: "normal",
  version: "1.0.0",
  documentation: { summary: overrides.description },
  examples: [],
  compatibility: { minHubVersion: "mak-studio-events-v1" },
  breakingChanges: [],
  notes: [],
  ...overrides,
});

export const STUDIO_BUS_EVENT_CATALOG = [
  baseManifest({
    eventId: "selection.changed",
    name: "SelectionChanged",
    category: "workspace",
    description: "Active selection changed in Explorer, Outline, or Workspace.",
    payload: { selectionId: "string|null", entryId: "string|null", entryType: "string|null", source: "string" },
    origin: "explorer",
    consumers: ["inspector", "properties", "outline", "workspace"],
  }),
  baseManifest({
    eventId: "component.created",
    name: "ComponentCreated",
    category: "component",
    description: "A Studio component entry was created.",
    payload: { componentId: "string", entryId: "string", parentId: "string|null", source: "string" },
    origin: "designer",
    consumers: ["explorer", "outline", "preview", "history"],
  }),
  baseManifest({
    eventId: "component.deleted",
    name: "ComponentDeleted",
    category: "component",
    description: "A Studio component entry was deleted.",
    payload: { componentId: "string", entryId: "string", source: "string" },
    origin: "designer",
    consumers: ["explorer", "outline", "preview", "history"],
  }),
  baseManifest({
    eventId: "component.updated",
    name: "ComponentUpdated",
    category: "component",
    description: "A Studio component entry was updated.",
    payload: { componentId: "string", entryId: "string", changes: "object", source: "string" },
    origin: "designer",
    consumers: ["inspector", "preview", "history"],
  }),
  baseManifest({
    eventId: "property.changed",
    name: "PropertyChanged",
    category: "property",
    description: "A property value changed in the Properties panel or designer.",
    payload: { propertyId: "string", entryId: "string", previousValue: "unknown", nextValue: "unknown", source: "string" },
    origin: "properties",
    consumers: ["inspector", "preview", "history"],
  }),
  baseManifest({
    eventId: "layout.changed",
    name: "LayoutChanged",
    category: "layout",
    description: "Layout structure changed in Layout Studio.",
    payload: { layoutId: "string", entryId: "string", changeType: "string", source: "string" },
    origin: "layout-designer",
    consumers: ["preview", "outline", "history"],
    priority: "high",
  }),
  baseManifest({
    eventId: "theme.changed",
    name: "ThemeChanged",
    category: "theme",
    description: "Active design theme changed.",
    payload: { themeId: "string", previousThemeId: "string|null", source: "string" },
    origin: "design-system",
    consumers: ["preview", "properties"],
  }),
  baseManifest({
    eventId: "token.changed",
    name: "TokenChanged",
    category: "theme",
    description: "A design token value changed.",
    payload: { tokenId: "string", themeId: "string|null", source: "string" },
    origin: "design-system",
    consumers: ["preview", "properties"],
  }),
  baseManifest({
    eventId: "manifest.updated",
    name: "ManifestUpdated",
    category: "component",
    description: "Component manifest metadata was updated.",
    payload: { componentId: "string", manifestVersion: "string", source: "string" },
    origin: "design-system",
    consumers: ["explorer", "properties", "preview"],
  }),
  baseManifest({
    eventId: "publish.started",
    name: "PublishStarted",
    category: "publish",
    description: "MDP publish flow started.",
    payload: { moduleId: "string", versionId: "string|null", source: "string" },
    origin: "publish-center",
    consumers: ["runtime-console", "preview"],
    priority: "high",
  }),
  baseManifest({
    eventId: "publish.completed",
    name: "PublishCompleted",
    category: "publish",
    description: "MDP publish flow completed.",
    payload: { moduleId: "string", versionId: "string", success: "boolean", source: "string" },
    origin: "publish-center",
    consumers: ["runtime-console", "preview", "explorer"],
    priority: "high",
  }),
  baseManifest({
    eventId: "preview.updated",
    name: "PreviewUpdated",
    category: "preview",
    description: "Preview engine refreshed compiled output.",
    payload: { moduleId: "string", previewId: "string|null", source: "string" },
    origin: "preview",
    consumers: ["runtime-console", "inspector"],
  }),
  baseManifest({
    eventId: "history.undo",
    name: "UndoPerformed",
    category: "workspace",
    description: "Undo command executed on history stack.",
    payload: { commandLabel: "string", source: "string" },
    origin: "history",
    consumers: ["explorer", "preview", "properties"],
  }),
  baseManifest({
    eventId: "history.redo",
    name: "RedoPerformed",
    category: "workspace",
    description: "Redo command executed on history stack.",
    payload: { commandLabel: "string", source: "string" },
    origin: "history",
    consumers: ["explorer", "preview", "properties"],
  }),
  baseManifest({
    eventId: "dock.changed",
    name: "DockChanged",
    category: "dock",
    description: "Dock panel visibility or zone changed.",
    payload: { panelId: "string", zone: "string", visible: "boolean", source: "string" },
    origin: "dock",
    consumers: ["shell"],
  }),
  baseManifest({
    eventId: "workspace.changed",
    name: "WorkspaceChanged",
    category: "workspace",
    description: "Active workspace context changed.",
    payload: { workspaceId: "string", moduleId: "string|null", source: "string" },
    origin: "shell",
    consumers: ["explorer", "preview", "designer"],
    priority: "high",
  }),
  baseManifest({
    eventId: "designer.active.changed",
    name: "ActiveDesignerChanged",
    category: "workspace",
    description: "Active designer plugin changed.",
    payload: { designerId: "string", previousDesignerId: "string|null", source: "string" },
    origin: "shell",
    consumers: ["dock", "explorer", "workspace"],
    priority: "high",
  }),
];

export default STUDIO_BUS_EVENT_CATALOG;
